### ISSUE TITLE
invalid start byte

### ISSUE THREAD

**Issue by ZQyou** [xalt/xalt#55] opened 2021-07-01 17:40 UTC
The ingest failed with he following error recently: 

```
################################################################
XALT Git Version: XALT 2.10.18
################################################################

-------------------+--------Traceback (most recent call last):
  File "/users/PZS0710/zyou/opt/xalt/2.10.18-syslog/sbin/xalt_syslog_to_db.py", line 564, in <module>
    if ( __name__ == '__main__'): main()
  File "/users/PZS0710/zyou/opt/xalt/2.10.18-syslog/sbin/xalt_syslog_to_db.py", line 483, in main
    for line in f:
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 2102: invalid start byte

```
The problematic entries can be found here: https://github.com/ZQyou/xalt_test/blob/main/2021/owens/invalid_start_byte.log

It works fine with python 2.7.

**Comment by rtmclay** [comment] 2021-07-01 20:23
The issue is that Python 3 handle files very differently w.r.t. Unicode.  It turns out that:
```
    for line in f: 
```
Is doing a lot behind the scenes.  I had to change this to:
```
     for bline in f:
        try:
          line = bline.decode()
        except UnicodeDecodeError as e:
          continue
```
to be able to catch the UnicodeDecodeError.  I did not see an exception in python 3.8 but this change is a safer way to handle the problem. 

Please try XALT-2.10.22 to see if it works for you.

**Comment by ZQyou** [comment] 2021-07-02 15:19
I encountered an error with checking reverseMap. I note that you have changed reverse map file name from `jsonReverseMapT.json` to `xalt_rmapT.json`.  When did this happen? Our site still uses `jsonReverseMapT.json`.

**Comment by rtmclay** [comment] 2021-07-02 17:31
What error do you see?  The change to use xalt_rmapT.json  happened a long time ago.  I found it in use as early as XALT 2.1

The use of jsonReverseMapT.json was used with XALT 1+ but not XALT 2.  The current documentation only describes creating and using xalt_rmapT.json

**Comment by rtmclay** [comment] 2021-07-02 19:30
I thought about it some more.  There are two places where XALT uses the reverse map.  One is when linking to figure out the function tracking.  That one uses xalt_rmapT.json.

The second one is when figuring out when converting paths into modules.  That one uses either jsonReverseMapT.json or xalt_rmapT.json.  That has not changed.  It should still work.  So what error did you get?

**Comment by rtmclay** [comment] 2021-07-02 19:52
I found where the problem is.  When pushing XALT 2.10.22, I added a test to check that the argument passed in for  reverseMapD
was a directory and not a file.  I will fix this.  Still, I would encourage switching to xalt_rmapT.json

**Comment by ZQyou** [comment] 2021-07-02 20:26
I think the error I got is related to this change: https://github.com/xalt/xalt/commit/8200102e86f45ad61e34493716ed6b47e8745e36#diff-4054d2672746cd302d7bedc0e2ab4f6fb513e2883343dbaeb6ccee0d8febe41a

We will  switch to xalt_rmapT.json.  Thank you.

**Comment by rtmclay** [comment] 2021-07-05 11:41
Thanks for the bug report on failing to ingest files when using jsonReverseMapT.json as the reverseMap.  This is now fixed for me.

**Closed** 2021-07-08 20:56 UTC
